// Generated by scripts/generate-error-code-artifacts.mjs. Do not edit manually.
import type { ErrorCode } from './error-codes.gen.js';

type DevErrorDetails = {
	title: string;
	summary: string;
};

export const DEV_ERRORS: Record<ErrorCode, DevErrorDetails> | undefined = __SHADERPAD_DEV__
	? {
			'0': {
				title: 'WebGL2 Context Unavailable',
				summary: 'ShaderPad could not create a WebGL2 rendering context.',
			},
			'1': {
				title: 'Program Allocation Failed',
				summary: 'ShaderPad could not allocate a WebGL program object.',
			},
			'2': {
				title: 'Program Link Failed',
				summary: 'ShaderPad compiled the shaders but failed to link them into a WebGL program.',
			},
			'3': {
				title: 'Unknown GL Constant',
				summary: 'ShaderPad received a WebGL constant name it does not recognize.',
			},
			'4': {
				title: 'Shader Compilation Failed',
				summary: 'A vertex or fragment shader failed to compile.',
			},
			'5': {
				title: 'Texture Units Exhausted',
				summary: 'ShaderPad tried to reserve more texture units than this device exposes.',
			},
			'6': {
				title: 'Float Color Buffer Extension Missing',
				summary: 'ShaderPad requested a float render texture, but EXT_color_buffer_float is unavailable.',
			},
			'7': {
				title: 'Uniform Already Initialized',
				summary: 'ShaderPad was asked to register a uniform name that was already registered.',
			},
			'8': {
				title: 'Invalid Uniform Type',
				summary: 'ShaderPad received an unsupported uniform type string.',
			},
			'9': {
				title: 'Uniform Array Length Mismatch',
				summary: 'ShaderPad was asked to initialize a uniform array with the wrong number of elements.',
			},
			'10': {
				title: 'Uniform Array Update Expected An Array',
				summary: 'ShaderPad attempted to update a uniform array, but the provided value was not an array.',
			},
			'11': {
				title: 'Uniform Array Update Too Large',
				summary: 'ShaderPad received more uniform array elements than the initialized array can hold.',
			},
			'12': {
				title: 'Uniform Array Element Size Mismatch',
				summary: 'At least one uniform array element has the wrong scalar or vector length.',
			},
			'13': {
				title: 'Uniform Array Start Index Invalid',
				summary: 'ShaderPad could not find the requested starting index for a uniform array.',
			},
			'14': {
				title: 'Uniform Value Length Invalid',
				summary: 'ShaderPad received a scalar or vector uniform update with the wrong component count.',
			},
			'15': {
				title: 'Texture Allocation Failed',
				summary: 'ShaderPad could not create a WebGL texture object.',
			},
			'16': {
				title: 'Texture Already Initialized',
				summary: 'ShaderPad was asked to initialize a texture name that is already registered.',
			},
			'17': {
				title: 'Texture Source Dimensions Invalid',
				summary: 'ShaderPad could not determine valid width and height values for the texture source.',
			},
			'18': {
				title: 'Texture Not Initialized',
				summary: 'ShaderPad was asked to update a texture name that has not been initialized.',
			},
			'19': {
				title: 'Uniform Missing During Initialization',
				summary:
					'ShaderPad could not initialize a uniform because the shader program does not contain that symbol.',
			},
			'20': {
				title: 'Uniform Missing During Update',
				summary:
					'ShaderPad could not update a uniform because the shader program does not contain that symbol.',
			},
			'60': {
				title: 'Face Mask Renderer Context Unavailable',
				summary: 'The face plugin could not create the offscreen WebGL2 context used for face-mask rendering.',
			},
			'61': {
				title: 'Face Mask Shader Setup Failed',
				summary: 'The face plugin could not build the shaders it uses for face-mask rendering.',
			},
			'62': {
				title: 'Face Mask Renderer Initialization Failed',
				summary: 'The face plugin could not finish setting up its internal face-mask renderer.',
			},
		}
	: undefined;
