// Generated by scripts/generate-error-code-artifacts.mjs. Do not edit manually.
export type ErrorCode = number;

export const ERROR_DOCS_BASE_URL = 'https://mry.ac/s/';

export function errorUrl(code: ErrorCode) {
	return `${ERROR_DOCS_BASE_URL}${code}`;
}
